### ISSUE TITLE
Deprecated selector in rad-syntax\index.less

### ISSUE THREAD

**Issue by LunarTwilight** [cliambrown/vivid-syntax#1]
In `rad-syntax\index.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor,
:host` => `atom-text-editor,atom-text-editor`

* `atom-text-editor .wrap-guide,
:host .wrap-guide` => `atom-text-editor .wrap-guide,atom-text-editor .wrap-guide`

* `atom-text-editor .indent-guide,
:host .indent-guide` => `atom-text-editor .indent-guide,atom-text-editor .indent-guide`

* `atom-text-editor .invisible-character,
:host .invisible-character` => `atom-text-editor .invisible-character,atom-text-editor .invisible-character`

* `atom-text-editor .gutter,
:host .gutter` => `atom-text-editor .gutter,atom-text-editor .gutter`

* `atom-text-editor .gutter .line-number.cursor-line,
:host .gutter .line-number.cursor-line` => `atom-text-editor .gutter .line-number.cursor-line,atom-text-editor .gutter .line-number.cursor-line`

* `atom-text-editor .gutter .line-number.cursor-line-no-selection,
:host .gutter .line-number.cursor-line-no-selection` => `atom-text-editor .gutter .line-number.cursor-line-no-selection,atom-text-editor .gutter .line-number.cursor-line-no-selection`

* `atom-text-editor .invisible,
:host .invisible` => `atom-text-editor .invisible,atom-text-editor .invisible`

* `atom-text-editor .cursor,
:host .cursor` => `atom-text-editor .cursor,atom-text-editor .cursor`

* `atom-text-editor .selection .region,
:host .selection .region` => `atom-text-editor .selection .region,atom-text-editor .selection .region`

* `atom-text-editor .search-results .marker .region,
:host .search-results .marker .region` => `atom-text-editor .search-results .syntax--marker .region,atom-text-editor .search-results .syntax--marker .region`

* `atom-text-editor .search-results .marker.current-result .region,
:host .search-results .marker.current-result .region` => `atom-text-editor .search-results .syntax--marker.current-result .region,atom-text-editor .search-results .syntax--marker.current-result .region`

* `.source.js,
.variable.js,
.function-call.js` => `.syntax--source.syntax--js,
.syntax--variable.syntax--js,
.syntax--function-call.syntax--js`

* `.punctuation.definition,
.meta.brace,
.meta.delimiter,
.punctuation.terminator` => `.syntax--punctuation.syntax--definition,
.syntax--meta.syntax--brace,
.syntax--meta.syntax--delimiter,
.syntax--punctuation.syntax--terminator`

* `.support.constant.js,
.support.function.js,
.entity.name.function.js` => `.syntax--support.syntax--constant.syntax--js,
.syntax--support.syntax--function.syntax--js,
.syntax--entity.syntax--name.syntax--function.syntax--js`

* `.punctuation.separator.key-value.json   .string` => `.syntax--punctuation.syntax--separator.syntax--key-value.syntax--json   .syntax--string`

* `.meta.property-value.css` => `.syntax--meta.syntax--property-value.syntax--css`

* `.punctuation.separator.key-value.css` => `.syntax--punctuation.syntax--separator.syntax--key-value.syntax--css`

* `.comment` => `.syntax--comment`

* `.keyword` => `.syntax--keyword`

* `.keyword.other.special-method` => `.syntax--keyword.syntax--other.syntax--special-method`

* `.storage` => `.syntax--storage`

* `.constant` => `.syntax--constant`

* `.constant.character.escape,
.co

**Comment by thiagolucio** [comment]
same to me

**Comment by LunarTwilight** [comment]
Duplicate of #2
